package gabrielgrs.com.br.projetoexemplo;

import android.graphics.Color;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.TextView;

public class MainActivity extends AppCompatActivity {

//   TODO (2) AQUI ESTOU CRIANDO UMA VARIAVEL DO TIPO TEXTVIEW QUE IRÁ ARMAZENAR O NOSSO RESOURCE QUE CRIAMOS NO XML
    private TextView mTesteTextView;


    // TODO ESSE METODO É EXECUTADO TODAS AS VEZES QUE CRIARMOS A NOSSA ACTIVITY(TELA), OU SEJA. SE SAIRMOS DA TELA OU FECHARMOS O APP E ABRIRMOS DE NOVO ELE EXECUTARA TUDO QUE ESTÁ NESSE METODO
    // TODO ALEM DESSE METODO TEMOS VARIOS OUTROS QUE SAO EXECUTADOS DESSA FORMA
    // TODO ONRESUME QUANDO DAMOS ONPAUSE E DEPOIS VOLTAMOS PARA ELA, EXEMPLO QUANDO APENAS MINIMIZAMOS ELA
    // TODO ONPAUSE QUANDO MINIZAMOS O APP
    // TODO ONRESULT QUANDO ESTAMOS ESPERANDO QUE ALGUMA ACAO SEJA TOMADA E EXISTE ALGUM LISTENER PARA ESSA ACAO QUE DEVE SER TOMADA FORA DO APP. EXEMPLO QUANDO CHAMAMOS A ACTIVITY DO ANDROID DE TIRAR FOTOS E ESTAMOS ESPERANDO ESSA FOTO VOLTAR PARA NOSSO AP
    // TODO ENTRE OUTROS...
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        // TODO (3) AGORA ESTOU VINCULANDO MINHA VARIAVEL QUE CRIEI NO TODO (2) COM NOSSO RECURSO QUE COLOCAMOS NO TODO (1)
        mTesteTextView = findViewById(R.id.textview_de_teste);

        // TODO (4) AGORA QUE TEMOS NOSSO CAMPO DE TEXTO QUE ESTÁ SENDO EXIBIDO NA TELA ARMAZENADO EM UMA VARIAVEL
        // TODO CONSEGUIMOS MANIPULA-LO DA FORMA COMO PRECISARMOS, EXEMPLO: VAMOS ALTERAR O TEXTO PARA TESTE TEXTVIEW
        mTesteTextView.setText(R.string.teste_textview);
        // TODO NA HORA DE COLOCAR O TEXTO EU UTILIZEI UM OUTRO JEITO DE ARMAZENAR RECURSO, QUE É O ARQUIVO DE STRINGS
        // TODO TODA VEZ QUE COLOCAMOS TEXTO DE STRING EM HARDEN CODE O LINT(SISTEMA DE VERIFICACAO DE CODIGO DO ANDROID STUDIO) NOS RECLAMA AVISANDO QUE ISSO NAO É UMA BOA PRATICA
        // TODO PARA ACESSAR ESSE ARQUIVO E ADICIONAR NOVAS STRINGS É SÓ SEGUIR O CAMINHO: APP/RES/VALUES/STRINGS.XML
        // TODO OU APENAS CLICAR COM BOTAO DO MEIO DO MOUSE SOBRE A STRING
        // TODO OU SEGURAR A TECLA CTRL E CLICAR COM BOTAO ESQUERDO DO MOUSE SOBRE A STRING
        // TODO OU APENAR AS TECLAS CTRL + N E DIGITAR STRINGS.XML
        // TODO OU APENAR AS TECLAS SHIFT + SHIFT E DIGITAR STRINGS.XML


        // TODO ALTERAR A COR DO TEXTO
        mTesteTextView.setTextColor(Color.BLUE);

        // TODO ALTERAR O TAMANHO DO TEXTO
        mTesteTextView.setTextSize(40);

        // TODO ENFIM.. CONSEGUIMOS ALTERAR BASICAMENTE TODAS AS PROPRIEDADES DO NOSSO TEXTO(OU QUALQUER OUTRO TIPO DE VIEW) POR AQUI
        // TODO EXPERIEMENTE DIGITAR mTesteTextView.set E DEPOIS DE CTRL + BARRA DE ESPACO E EXPLORE AS POSSIBILIDADES
    }
}
